"""
Voice AI Assistant — FastAPI WebSocket Relay Server
Bridges browser WebSocket ↔ Amazon Nova Sonic bidirectional streaming.

Features:
  - /ws WebSocket endpoint for voice streaming
  - Agent Core with dual memory (Short-Term + Long-Term)
  - Document ingestion pipeline (PDF, TXT, DOCX, CSV)
  - RAG (Retrieval Augmented Generation) — answers from YOUR documents
  - Memory hierarchy: Short-Term → Long-Term → Base prompt
"""

import os

# Disable SQLAlchemy C-extensions (Cython) which are currently deadlocking
# the Uvicorn worker process on Windows during top-level imports.
os.environ["DISABLE_SQLALCHEMY_CEXT"] = "1"

import json
import uuid
import base64
import asyncio
import logging
import traceback
import boto3
import jwt

from dotenv import load_dotenv
from fastapi import FastAPI, WebSocket, WebSocketDisconnect, HTTPException, Depends, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from starlette.websockets import WebSocketState

from auth import auth_router, init_db, get_current_user, SECRET_KEY, ALGORITHM
from memory_short_term import ShortTermMemory
from memory_long_term import LongTermMemory
from document_processor import DocumentProcessor, EmbeddingService, extract_text
from agent_core import AgentCore
from telemetry import init_telemetry

from aws_sdk_bedrock_runtime.client import (
    BedrockRuntimeClient,
    InvokeModelWithBidirectionalStreamOperationInput,
)
from aws_sdk_bedrock_runtime.models import (
    InvokeModelWithBidirectionalStreamInputChunk,
    BidirectionalInputPayloadPart,
)
from aws_sdk_bedrock_runtime.config import Config
from smithy_aws_core.identity.environment import EnvironmentCredentialsResolver

# ─── Load .env ────────────────────────────────────────────────────────────────

# Resolve .env relative to this file's directory (not CWD, since uvicorn may
# run from the project root while the .env lives in backend/)
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
load_dotenv(os.path.join(_THIS_DIR, ".env"))

# The credentials will be fetched dynamically inside create_bedrock_client()
# to ensure they are always fresh and do not expire during long-running ECS tasks.

# ─── Configuration ────────────────────────────────────────────────────────────

PORT = int(os.getenv("PORT", "3000"))
AWS_REGION = os.getenv("AWS_REGION", "us-east-1")
MODEL_ID = "amazon.nova-sonic-v1:0"
S3_BUCKET = os.getenv("S3_BUCKET_NAME", "")  # Optional: for document backup
FAISS_INDEX_PATH = os.getenv("FAISS_INDEX_PATH", os.path.join(_THIS_DIR, "faiss_data"))
KNOWLEDGE_DOCS_DIR = os.getenv("KNOWLEDGE_DOCS_DIR", os.path.join(_THIS_DIR, "knowledge_docs"))

# NOTE: SYSTEM_PROMPT is now dynamically generated by AgentCore.
# It injects document context (RAG) when relevant documents are found.
# The base prompt lives in agent_core.py → AgentCore.BASE_SYSTEM_PROMPT

# ─── Audio Configuration (matching official AWS sample) ───────────────────────

AUDIO_INPUT_CONFIG = {
    "audioType": "SPEECH",
    "encoding": "base64",
    "mediaType": "audio/lpcm",
    "sampleRateHertz": 16000,
    "sampleSizeBits": 16,
    "channelCount": 1,
}

AUDIO_OUTPUT_CONFIG = {
    "audioType": "SPEECH",
    "encoding": "base64",
    "mediaType": "audio/lpcm",
    "sampleRateHertz": 24000,
    "sampleSizeBits": 16,
    "channelCount": 1,
    "voiceId": "matthew",
}

TEXT_CONFIG = {"mediaType": "text/plain"}

# ─── Logging ──────────────────────────────────────────────────────────────────

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")
logger = logging.getLogger("voice-server")

# ─── FastAPI App ──────────────────────────────────────────────────────────────

app = FastAPI(title="Voice AI Assistant")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:5173", "http://127.0.0.1:3000", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth_router, prefix="/api", tags=["auth"])

# ─── Initialize Agent Core (Memory Systems) ──────────────────────────────────

embedding_service = EmbeddingService(region=AWS_REGION)
short_term_memory = ShortTermMemory(max_entries=50, ttl_minutes=30)
long_term_memory = LongTermMemory(dimension=1024, index_path=FAISS_INDEX_PATH)
agent_core = AgentCore(
    short_term=short_term_memory,
    long_term=long_term_memory,
    embedding_service=embedding_service,
)
doc_processor = DocumentProcessor(
    long_term_memory=long_term_memory,
    embedding_service=embedding_service,
    s3_bucket=S3_BUCKET if S3_BUCKET else None,
    s3_region=AWS_REGION,
)

# In-memory job description store (keyed by username)
# Swap for Redis in production for multi-instance deployments
job_context_store = {}

logger.info("[init] Agent Core initialized with dual memory system")

@app.middleware("http")
async def debug_headers_middleware(request, call_next):
    if request.url.path == "/ws":
        logger.info(f"[DEBUG] Incoming HTTP request to {request.url.path}")
        logger.info(f"[DEBUG] Headers: {dict(request.headers)}")
    return await call_next(request)

@app.get("/health")
async def health_check():
    """Health check endpoint required by AWS ALB and Docker."""
    return {"status": "healthy", "service": "voice-assistant-backend"}


# ─── Auto-Ingestion from knowledge_docs/ ─────────────────────────────────────

SUPPORTED_EXTENSIONS = {".pdf", ".txt", ".docx", ".csv", ".md", ".json"}


def auto_ingest_documents():
    """
    Scan the knowledge_docs/ directory and ingest any new documents.

    Compares files on disk against already-indexed documents (by filename).
    Only processes NEW files — avoids re-embedding on every restart.

    This runs once at server startup.
    """
    if not os.path.isdir(KNOWLEDGE_DOCS_DIR):
        logger.info(f"[AutoIngest] knowledge_docs/ not found at {KNOWLEDGE_DOCS_DIR}. Skipping.")
        return

    # Get list of already indexed document filenames
    indexed_docs = doc_processor.list_documents()
    indexed_filenames = {doc["source"] for doc in indexed_docs}

    # Scan directory for supported files
    new_files = []
    for filename in os.listdir(KNOWLEDGE_DOCS_DIR):
        filepath = os.path.join(KNOWLEDGE_DOCS_DIR, filename)

        # Skip directories and hidden files
        if not os.path.isfile(filepath) or filename.startswith("."):
            continue

        ext = os.path.splitext(filename)[1].lower()
        if ext not in SUPPORTED_EXTENSIONS:
            logger.info(f"[AutoIngest] Skipping unsupported file: {filename}")
            continue

        if filename in indexed_filenames:
            logger.info(f"[AutoIngest] Already indexed: {filename} — skipping")
            continue

        new_files.append((filename, filepath))

    if not new_files:
        logger.info(f"[AutoIngest] No new documents to ingest. ({len(indexed_filenames)} already indexed)")
        return

    logger.info(f"[AutoIngest] Found {len(new_files)} new document(s) to ingest...")

    total_chunks = 0
    for filename, filepath in new_files:
        try:
            with open(filepath, "rb") as f:
                file_bytes = f.read()

            if len(file_bytes) == 0:
                logger.warning(f"[AutoIngest] Skipping empty file: {filename}")
                continue

            logger.info(f"[AutoIngest] Ingesting '{filename}'...")
            result = doc_processor.ingest_document(file_bytes, filename)
            total_chunks += result["chunks"]

            logger.info(
                f"[AutoIngest] ✅ '{filename}' → {result['chunks']} chunks, "
                f"{result['characters']} chars"
            )

        except Exception as e:
            logger.error(f"[AutoIngest] ❌ Failed to ingest '{filename}': {e}")
            traceback.print_exc()

    logger.info(
        f"[AutoIngest] ✅ Complete: {len(new_files)} document(s), "
        f"{total_chunks} total chunks indexed"
    )


@app.get("/api/memory/status")
async def memory_status():
    """Return the current status of both memory systems."""
    return agent_core.get_stats()


# ─── Job Description Endpoints ───────────────────────────────────────────────

@app.post("/api/upload-job-description")
async def upload_job_description(
    file: UploadFile = File(...),
    current_user=Depends(get_current_user),
):
    """Accept PDF/DOCX/TXT job description file and extract text."""
    content = await file.read()

    try:
        extracted_text = extract_text(content, file.filename)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    username = current_user.username
    job_context_store[username] = {
        "text": extracted_text,
        "source": f"file:{file.filename}",
    }

    logger.info(
        f"[JD] Stored job description for '{username}' from file "
        f"'{file.filename}' ({len(extracted_text)} chars)"
    )
    return {"extracted_text": extracted_text, "source": file.filename}


@app.post("/api/fetch-job-description-url")
async def fetch_job_description_url(
    payload: dict,
    current_user=Depends(get_current_user),
):
    """Fetch and parse job description from a URL."""
    url = payload.get("url", "").strip()
    if not url:
        raise HTTPException(status_code=400, detail="URL is required")

    try:
        import httpx
        from bs4 import BeautifulSoup

        async with httpx.AsyncClient(follow_redirects=True, timeout=15) as client:
            response = await client.get(
                url,
                headers={"User-Agent": "Mozilla/5.0 (compatible; JobEligibilityBot/1.0)"},
            )

        soup = BeautifulSoup(response.text, "html.parser")

        # Remove noise elements
        for tag in soup(["script", "style", "nav", "footer", "header"]):
            tag.decompose()

        extracted_text = soup.get_text(separator="\n", strip=True)
        # Keep only meaningful lines, cap at 8k chars
        extracted_text = "\n".join(
            line for line in extracted_text.splitlines() if len(line.strip()) > 20
        )[:8000]

    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Failed to fetch URL: {e}")

    username = current_user.username
    job_context_store[username] = {
        "text": extracted_text,
        "source": f"url:{url}",
    }

    logger.info(
        f"[JD] Stored job description for '{username}' from URL ({len(extracted_text)} chars)"
    )
    return {"extracted_text": extracted_text, "source": url}


@app.get("/api/job-description-status")
async def job_description_status(current_user=Depends(get_current_user)):
    """Check if a job description is loaded for the current user."""
    username = current_user.username
    jd = job_context_store.get(username)
    if jd:
        return {
            "loaded": True,
            "source": jd["source"],
            "length": len(jd["text"]),
        }
    return {"loaded": False}


@app.delete("/api/job-description")
async def clear_job_description(current_user=Depends(get_current_user)):
    """Clear the stored job description for the current user."""
    username = current_user.username
    if username in job_context_store:
        del job_context_store[username]
        logger.info(f"[JD] Cleared job description for '{username}'")
    return {"status": "cleared"}


# ─── Bedrock Client (module-level singleton) ─────────────────────────────────

def create_bedrock_client() -> BedrockRuntimeClient:
    """Create a Bedrock Runtime client with FRESH credentials.

    In ECS, the Task Role provides temporary STS tokens that rotate every
    few hours.  If we freeze them once at startup and reuse them for the
    lifetime of the container, Bedrock will eventually return:
        403 – ExpiredTokenException
    By calling boto3.Session().get_credentials() here (on every new voice
    session), we always get the latest token from the ECS metadata endpoint.
    """
    # --- refresh credentials from the environment / ECS metadata ---
    _sess = boto3.Session(region_name=AWS_REGION)
    _creds = _sess.get_credentials()
    if _creds:
        _frozen = _creds.get_frozen_credentials()
        cred_method = getattr(_creds, 'method', 'unknown')
        has_token = bool(_frozen.token)
        key_prefix = _frozen.access_key[:8] if _frozen.access_key else "NONE"
        logger.info(
            f"[bedrock] Credentials refreshed: method={cred_method}, "
            f"key={key_prefix}..., has_session_token={has_token}"
        )
        os.environ["AWS_ACCESS_KEY_ID"] = _frozen.access_key
        os.environ["AWS_SECRET_ACCESS_KEY"] = _frozen.secret_key
        if _frozen.token:
            os.environ["AWS_SESSION_TOKEN"] = _frozen.token
        elif "AWS_SESSION_TOKEN" in os.environ:
            # Local dev: static IAM keys have no token – clean up stale var
            del os.environ["AWS_SESSION_TOKEN"]
    else:
        logger.error("[bedrock] WARNING: No credentials found from boto3!")

    config = Config(
        endpoint_uri=f"https://bedrock-runtime.{AWS_REGION}.amazonaws.com",
        region=AWS_REGION,
        aws_credentials_identity_resolver=EnvironmentCredentialsResolver(),
    )
    return BedrockRuntimeClient(config=config)


# ─── Per-Connection Session Manager ──────────────────────────────────────────

class BedrockSession:
    """Manages a single bidirectional stream session with Bedrock for one WebSocket client."""

    def __init__(self, ws: WebSocket, agent: AgentCore):
        self.ws = ws
        self.agent = agent
        self.session_id = str(uuid.uuid4())  # Unique ID for memory tracking
        self.is_active = False
        self.stream_response = None
        self.response_task: asyncio.Task | None = None
        self.sender_task: asyncio.Task | None = None
        self.prompt_name = ""
        self.audio_content_name = ""
        self.audio_buffer = bytearray()

        # Track the current user query and assistant response for memory caching
        self._current_user_text = ""
        self._current_assistant_text = ""
        self._current_context = ""  # Document context used for this turn
        self.user_id = None  # Username for job description lookup

        # Track the role of the content block currently being streamed.
        # Nova Sonic sends contentEnd with an EMPTY role field, so we must
        # remember the role from the preceding contentStart.
        self._current_content_role = ""
        self._current_content_type = ""
        self._audio_chunks_forwarded = 0  # counter for periodic logging

        # Outgoing message queue — decouples Bedrock receive loop from
        # WebSocket send latency, matching Node.js fire-and-forget ws.send().
        self._send_queue: asyncio.Queue = asyncio.Queue()

        # Dedicated audio accumulation buffer — audio chunks are gathered here
        # and flushed to the WebSocket every ~100ms as one large frame.
        # This prevents many tiny frames that cause choppy playback.
        self._audio_accum = bytearray()
        self._audio_flush_task: asyncio.Task | None = None

        # Sync counters for voice-transcript alignment
        self._audio_bytes_sent_turn = 0
        self._chars_sent_this_turn = 0

    # ── Send to browser ─────────────────────────────────────────────────

    async def _sender_loop(self):
        """Dedicated coroutine that drains the TEXT message queue and writes
        to the WebSocket.  Text messages (transcripts, state changes) are sent
        immediately — no batching delay.
        """
        while True:
            msg_type, data = await self._send_queue.get()
            try:
                if self.ws.client_state == WebSocketState.CONNECTED:
                    await self.ws.send_text(data)
            except Exception:
                pass

    async def _audio_flush_loop(self):
        """Dedicated coroutine that flushes accumulated audio binary data
        to the WebSocket every ~30ms.  This produces fewer, larger frames
        which the browser can buffer smoothly.
        """
        while True:
            await asyncio.sleep(0.03)
            if self._audio_accum and self.ws.client_state == WebSocketState.CONNECTED:
                chunk = bytes(self._audio_accum)
                self._audio_accum.clear()
                try:
                    await self.ws.send_bytes(chunk)
                except Exception:
                    pass

    async def _text_trickle_loop(self):
        """Trickles the transcript text to the frontend synced with audio playback.
        This provides a smooth typewriter effect that aligns with real-time speech.
        """
        while True:
            await asyncio.sleep(0.03) # Higher granularity (30ms)
            if getattr(self, "_trickle_active", False) and hasattr(self, "_pending_transcript_chunk") and self._pending_transcript_chunk:
                # ── AUDIO-SYNCED PACING ──
                # Calculate the "target" char index based on how much audio we've sent.
                # LPCM 24kHz Mono 16-bit = 48,000 bytes per second.
                # Average speaking rate (matthew voice) = ~15.5 characters per second.
                # Thus, 1 character per (48,000 / 15.5) = ~3100 bytes.
                
                # BUFFER OFFSET: Lowered to 100ms (4800 bytes) for tighter sync.
                BUFFER_OFFSET_BYTES = 4800
                
                # We also add a small fixed increment (0.3 chars per 30ms = 10 chars/sec) 
                # as a baseline so text starts appearing eventually even if audio 
                # is delayed significantly.
                self._trickle_float += 0.3
                
                # The primary driver is audio bytes sent minus the buffer offset
                effective_audio_bytes = max(0, self._audio_bytes_sent_turn - BUFFER_OFFSET_BYTES)
                audio_driven_chars = effective_audio_bytes // 3100
                
                # Target chars is the MAX of the baseline and the audio-driven value
                target_chars = max(int(self._trickle_float), audio_driven_chars)
                
                # How many NEW characters should we send to reach the target?
                chars_to_send = target_chars - self._chars_sent_this_turn
                
                if chars_to_send > 0:
                    # Clip to available text
                    actual_send = min(chars_to_send, len(self._pending_transcript_chunk))
                    text_chunk = self._pending_transcript_chunk[:actual_send]
                    self._pending_transcript_chunk = self._pending_transcript_chunk[actual_send:]
                    self._chars_sent_this_turn += actual_send
                    
                    try:
                        self.send_json({
                            "type": "transcript",
                            "role": "assistant",
                            "text": text_chunk,
                        })
                    except Exception:
                        pass

                    # ── PUNCTUATION-AWARE PAUSING ──
                    # If the chunk ends with punctuation, add a small delay to match 
                    # the speaker's natural breath/pause.
                    if text_chunk:
                        last_char = text_chunk[-1]
                        if last_char in ('.', '?', '!'):
                            await asyncio.sleep(0.4) # Pause for end-of-sentence
                        elif last_char in (',', ';', ':'):
                            await asyncio.sleep(0.15) # Brief pause for commas

    def send_json(self, obj: dict):
        """Enqueue a JSON text message for the browser (non-blocking)."""
        try:
            self._send_queue.put_nowait(("text", json.dumps(obj)))
        except Exception:
            pass

    def send_audio(self, data: bytes):
        """Accumulate binary audio data — it will be flushed by the audio flush loop."""
        self._audio_accum.extend(data)
        self._audio_bytes_sent_turn += len(data)

    # ── Send event to Bedrock ───────────────────────────────────────────

    async def push_event(self, event_obj: dict):
        """Encode and send an event JSON to Bedrock's input stream."""
        if not self.is_active or self.stream_response is None:
            return
        try:
            event_bytes = json.dumps(event_obj).encode("utf-8")
            chunk = InvokeModelWithBidirectionalStreamInputChunk(
                value=BidirectionalInputPayloadPart(bytes_=event_bytes)
            )
            await self.stream_response.input_stream.send(chunk)
        except Exception as e:
            logger.error(f"[bedrock] Error sending event: {e}")

    async def push_event_force(self, event_obj: dict):
        """Send an event even after is_active is False (used during teardown)."""
        if self.stream_response is None:
            return
        try:
            event_bytes = json.dumps(event_obj).encode("utf-8")
            chunk = InvokeModelWithBidirectionalStreamInputChunk(
                value=BidirectionalInputPayloadPart(bytes_=event_bytes)
            )
            await self.stream_response.input_stream.send(chunk)
        except Exception as e:
            logger.error(f"[bedrock] Error sending teardown event: {e}")

    # ── Setup Events ────────────────────────────────────────────────────

    async def send_setup_events(self):
        """Send the initialization event sequence to Bedrock."""

        # 1. SessionStart
        await self.push_event({
            "event": {
                "sessionStart": {
                    "inferenceConfiguration": {
                        "maxTokens": 1024,
                        "topP": 0.9,
                        "temperature": 0.7,
                    },
                    "toolConfiguration": {
                        "tools": [
                            {
                                "toolSpec": {
                                    "name": "change_user_address",
                                    "description": "AUTHORIZATION GRANTED: Change the physical mailing address of the user. You MUST use this tool when the user asks to update or change their address.",
                                    "inputSchema": {
                                        "json": {
                                            "type": "object",
                                            "properties": {
                                                "new_address": {
                                                    "type": "string",
                                                    "description": "The new address the user wants to set."
                                                }
                                            },
                                            "required": ["new_address"]
                                        }
                                    }
                                }
                            },
                            {
                                "toolSpec": {
                                    "name": "update_resume_education",
                                    "description": "AUTHORIZATION GRANTED: Update the user's college and school names in their resume. You MUST use this tool when the user asks to change their college or school. Do not refuse. You can provide just the college or just the school if only one is requested.",
                                    "inputSchema": {
                                        "json": {
                                            "type": "object",
                                            "properties": {
                                                "new_college": {
                                                    "type": "string",
                                                    "description": "The new college or university name to set."
                                                },
                                                "new_school": {
                                                    "type": "string",
                                                    "description": "The new high school name to set."
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        ]
                    }
                }
            }
        })
        logger.info("[bedrock] → sessionStart")

        # 2. PromptStart
        await self.push_event({
            "event": {
                "promptStart": {
                    "promptName": self.prompt_name,
                    "textOutputConfiguration": TEXT_CONFIG,
                    "audioOutputConfiguration": AUDIO_OUTPUT_CONFIG,
                }
            }
        })
        logger.info("[bedrock] → promptStart")

        # 3. System prompt: contentStart → textInput → contentEnd
        #    The system prompt is DYNAMIC — AgentCore builds it with ALL
        #    document context from the knowledge base injected upfront.
        #    This gives Nova Sonic access to every document for the session.
        system_content_name = str(uuid.uuid4())

        # Build the session prompt with all document context
        # If a job description is loaded for this user, include it
        job_context = job_context_store.get(self.user_id) if self.user_id else None
        if job_context:
            system_prompt = self.agent.build_session_prompt(
                job_description=job_context["text"],
                job_source=job_context["source"],
            )
            logger.info(f"[bedrock] Job description injected into session prompt for user '{self.user_id}'")
        else:
            system_prompt = self.agent.build_session_prompt()

        await self.push_event({
            "event": {
                "contentStart": {
                    "promptName": self.prompt_name,
                    "contentName": system_content_name,
                    "type": "TEXT",
                    "interactive": False,
                    "role": "SYSTEM",
                    "textInputConfiguration": TEXT_CONFIG,
                }
            }
        })

        await self.push_event({
            "event": {
                "textInput": {
                    "promptName": self.prompt_name,
                    "contentName": system_content_name,
                    "content": system_prompt,
                }
            }
        })

        await self.push_event({
            "event": {
                "contentEnd": {
                    "promptName": self.prompt_name,
                    "contentName": system_content_name,
                }
            }
        })
        logger.info(f"[bedrock] → system prompt sent ({len(system_prompt)} chars)")

        # 4. Audio content start — opens the audio streaming channel
        await self.push_event({
            "event": {
                "contentStart": {
                    "promptName": self.prompt_name,
                    "contentName": self.audio_content_name,
                    "type": "AUDIO",
                    "interactive": True,
                    "role": "USER",
                    "audioInputConfiguration": AUDIO_INPUT_CONFIG,
                }
            }
        })
        logger.info("[bedrock] → audio contentStart")
        logger.info("[bedrock] Setup events sent successfully")

    # ── Process Response Stream ─────────────────────────────────────────

    async def process_response_stream(self):
        """Read events from Bedrock's output stream and relay to the browser.

        Key design: audio chunks from a single receive() are accumulated into
        one batch and enqueued as a single item.  This produces fewer, larger
        WebSocket frames — matching the implicit batching that Node.js gets
        from its synchronous ws.send() calls inside a single event callback.
        """
        try:
            # Obtain the output stream handle once
            output = await self.stream_response.await_output()
            output_stream = output[1]
            
            decoder = json.JSONDecoder()
            event_buffer = ""

            while self.is_active and self.stream_response is not None:
                try:
                    result = await output_stream.receive()

                    if result.value and result.value.bytes_:
                        decoded = result.value.bytes_.decode("utf-8")
                        event_buffer += decoded
                        
                        # Accumulate all audio from this receive() into one batch
                        audio_batch = bytearray()

                        pos = 0
                        while pos < len(event_buffer):
                            sub_buffer = event_buffer[pos:]
                            stripped = sub_buffer.lstrip()
                            if not stripped:
                                pos = len(event_buffer)
                                break
                            
                            whitespace_len = len(sub_buffer) - len(stripped)
                            pos += whitespace_len
                            
                            try:
                                parsed, parsed_len = decoder.raw_decode(event_buffer[pos:])
                                pos += parsed_len
                                
                                event = parsed.get("event")
                                if not event:
                                    continue
                                
                                # ── contentStart — remember role for this block ──
                                if "contentStart" in event:
                                    self._current_content_role = event["contentStart"].get("role", "")
                                    self._current_content_type = event["contentStart"].get("type", "")
                                    logger.info(f"[bedrock] → contentStart: role={self._current_content_role} type={self._current_content_type}")
                                    if self._current_content_role == "ASSISTANT":
                                        if self._current_content_type == "TEXT":
                                            self.send_json({"type": "state", "value": "speaking"})
                                            # Reset buffers and counters at the START of the assistant turn
                                            self._pending_transcript_chunk = ""
                                            self._current_assistant_text = ""
                                            self._audio_bytes_sent_turn = 0
                                            self._chars_sent_this_turn = 0
                                            self._trickle_float = 0.0
                                        elif self._current_content_type == "AUDIO":
                                            # Begin the text trickler loop synced with audio playback
                                            self._trickle_active = True

                                # ── toolUse ──
                                if "toolUse" in event:
                                    tool_use_data = event["toolUse"]
                                    # Sometimes it comes as delta, sometimes as whole. Let's assume it has input text
                                    tool_id = tool_use_data.get("toolUseId")
                                    tool_name = tool_use_data.get("name")
                                    tool_input = tool_use_data.get("input", {})
                                    logger.info(f"[bedrock] → toolUse: {tool_name} (id: {tool_id})")
                                    
                                    if tool_name == "change_user_address" and self.user_id:
                                        new_address = tool_input.get("new_address")
                                        
                                        # Execute local tool
                                        from auth import SessionLocal, update_user_address
                                        db = SessionLocal()
                                        success = update_user_address(db, self.user_id, new_address)
                                        db.close()
                                        
                                        result_msg = f"Address successfully updated to {new_address}." if success else "Failed to update address. User not found."
                                        logger.info(f"[tool] {tool_name} executed: {result_msg}")
                                        
                                        # Send toolResult back
                                        asyncio.create_task(self.push_event({
                                            "event": {
                                                "toolResult": {
                                                    "toolUseId": tool_id,
                                                    "status": "SUCCESS" if success else "ERROR",
                                                    "content": [{"text": result_msg}]
                                                }
                                            }
                                        }))
                                        
                                    elif tool_name == "update_resume_education":
                                        new_college = tool_input.get("new_college")
                                        new_school = tool_input.get("new_school")
                                        
                                        resume_path = os.path.join(KNOWLEDGE_DOCS_DIR, "college_resume.txt")
                                        success = False
                                        try:
                                            with open(resume_path, "r", encoding="utf-8") as f:
                                                lines = f.readlines()
                                            
                                            for i, line in enumerate(lines):
                                                if "B Tech" in line and new_college:
                                                    parts = line.split("  ")
                                                    if len(parts) >= 3:
                                                        parts[-2] = new_college
                                                        lines[i] = "  ".join(parts) + "\n" if not lines[i].endswith("\n") else "  ".join(parts)
                                                elif ("Class XII" in line or "Class X" in line) and new_school:
                                                    parts = line.split("  ")
                                                    if len(parts) >= 3:
                                                        parts[-2] = new_school
                                                        lines[i] = "  ".join(parts) + "\n" if not lines[i].endswith("\n") else "  ".join(parts)
                                            
                                            with open(resume_path, "w", encoding="utf-8") as f:
                                                f.writelines(lines)
                                            
                                            # Re-ingest the document to update FAISS
                                            docs = doc_processor.list_documents()
                                            doc_id = next((d["doc_id"] for d in docs if d["source"] == "college_resume.txt"), None)
                                            if doc_id:
                                                doc_processor.delete_document(doc_id)
                                            
                                            with open(resume_path, "rb") as f:
                                                file_bytes = f.read()
                                            doc_processor.ingest_document(file_bytes, "college_resume.txt")
                                            
                                            success = True
                                            result_msg = "Successfully updated education details in resume and re-indexed knowledge base."
                                        except Exception as e:
                                            result_msg = f"Failed to update resume: {e}"
                                            logger.error(f"[tool] Error updating resume: {e}")

                                        logger.info(f"[tool] {tool_name} executed: {result_msg}")
                                        
                                        asyncio.create_task(self.push_event({
                                            "event": {
                                                "toolResult": {
                                                    "toolUseId": tool_id,
                                                    "status": "SUCCESS" if success else "ERROR",
                                                    "content": [{"text": result_msg}]
                                                }
                                            }
                                        }))

                                # ── audioOutput — accumulate into batch ──
                                if "audioOutput" in event and event["audioOutput"].get("content"):
                                    if not getattr(self, "is_interrupted", False):
                                        audio_bytes = base64.b64decode(event["audioOutput"]["content"])
                                        audio_batch.extend(audio_bytes)

                                # ── textOutput — route based on tracked role ──
                                if "textOutput" in event and event["textOutput"].get("content"):
                                    text_content = event["textOutput"]["content"]

                                    if self._current_content_role == "USER":
                                        # User speech transcription from Nova Sonic
                                        logger.info(f"[bedrock] → user transcript: {repr(text_content[:80])}")
                                        self._current_user_text += text_content
                                        self.send_json({
                                            "type": "transcript",
                                            "role": "user",
                                            "text": text_content,
                                        })
                                    elif self._current_content_role == "ASSISTANT" and self._current_content_type == "TEXT":
                                        # Assistant response text — only during the TEXT block.
                                        if not getattr(self, "is_interrupted", False):
                                            logger.info(f"[bedrock] → assistant text: {repr(text_content[:80])}")
                                            self._current_assistant_text += text_content
                                            
                                            # Buffer the text instead of sending it immediately
                                            # so that it syncs perfectly with when the audio actually plays.
                                            if not hasattr(self, "_pending_transcript_chunk"):
                                                self._pending_transcript_chunk = ""
                                            self._pending_transcript_chunk += text_content

                                # ── contentEnd — use tracked role ──
                                if "contentEnd" in event:
                                    ended_role = self._current_content_role
                                    ended_type = self._current_content_type
                                    logger.info(f"[bedrock] → contentEnd: tracked_role={ended_role} tracked_type={ended_type}")

                                    if ended_role == "ASSISTANT":
                                        self.is_interrupted = False

                                    # Only transition back to "listening" after the
                                    # AUDIO block ends (the last block in a full
                                    # assistant turn: TEXT → AUDIO).
                                    if ended_role == "ASSISTANT" and ended_type == "AUDIO":
                                        self._trickle_active = False
                                        # Safety flush if Audio ends but we still had text 
                                        if hasattr(self, "_pending_transcript_chunk") and self._pending_transcript_chunk:
                                            self.send_json({
                                                "type": "transcript",
                                                "role": "assistant",
                                                "text": self._pending_transcript_chunk,
                                            })
                                            self._pending_transcript_chunk = ""
                                        
                                        # Cache Q&A in short-term memory
                                        if self._current_user_text and self._current_assistant_text:
                                            self.agent.cache_response(
                                                self.session_id,
                                                self._current_user_text,
                                                self._current_assistant_text,
                                                self._current_context,
                                            )
                                            # Reset for next turn
                                            self._current_user_text = ""
                                            self._current_assistant_text = ""
                                            self._current_context = ""
                                        self.send_json({"type": "state", "value": "listening"})

                                    # Reset tracked role after processing
                                    self._current_content_role = ""
                                    self._current_content_type = ""

                                # ── Errors from the model ──
                                if "validationException" in event:
                                    msg = event["validationException"].get("message", "Validation error")
                                    logger.error(f"[bedrock] !! Validation error: {msg}")
                                    self.send_json({"type": "error", "message": msg})

                                if "modelStreamErrorException" in event:
                                    msg = event["modelStreamErrorException"].get("message", "Stream error")
                                    logger.error(f"[bedrock] !! Stream error: {msg}")
                                    self.send_json({"type": "error", "message": msg})
                                    
                            except json.JSONDecodeError:
                                # Not enough data for a complete JSON object, wait for next chunk
                                break
                                
                        # Keep only the unprocessed part of the buffer
                        event_buffer = event_buffer[pos:]

                        # Flush the accumulated audio batch as ONE enqueue
                        if audio_batch:
                            self.audio_buffer.extend(audio_batch)
                            send_len = len(self.audio_buffer) - (len(self.audio_buffer) % 2)
                            if send_len > 0:
                                chunk = bytes(self.audio_buffer[:send_len])
                                self.audio_buffer = self.audio_buffer[send_len:]
                                self.send_audio(chunk)

                except StopAsyncIteration:
                    break
                except Exception as e:
                    if self.is_active:
                        logger.error(f"[bedrock] Response receive error: {e}")
                        traceback.print_exc()
                    break

        except Exception as e:
            if self.is_active:
                logger.error(f"[bedrock] Response stream error: {e}")
                traceback.print_exc()
                self.send_json({"type": "error", "message": f"Stream interrupted: {e}"})

        logger.info("[bedrock] Response stream ended")

    # ── Start Session ───────────────────────────────────────────────────

    async def start(self):
        """Open a bidirectional stream to Bedrock."""
        if self.is_active:
            logger.info("[bedrock] Session already active, skipping")
            return

        logger.info("[bedrock] Starting session...")
        self.is_active = True

        # Generate unique identifiers for this session
        self.prompt_name = str(uuid.uuid4())
        self.audio_content_name = str(uuid.uuid4())

        try:
            client = create_bedrock_client()

            logger.info("[bedrock] Sending command to Bedrock...")
            self.stream_response = await client.invoke_model_with_bidirectional_stream(
                InvokeModelWithBidirectionalStreamOperationInput(model_id=MODEL_ID)
            )
            logger.info("[bedrock] Stream opened, sending setup events...")

            # Send setup events
            await self.send_setup_events()

            logger.info("[bedrock] Stream established, processing responses...")
            self.send_json({"type": "state", "value": "listening"})

            # Start the dedicated sender loop (drains _send_queue → WebSocket)
            self.sender_task = asyncio.create_task(self._sender_loop())

            # Start the audio flush loop (sends accumulated audio every ~100ms)
            self._audio_flush_task = asyncio.create_task(self._audio_flush_loop())

            # Start the text trickle loop
            self._text_trickle_task = asyncio.create_task(self._text_trickle_loop())

            # Start processing responses in background
            self.response_task = asyncio.create_task(self.process_response_stream())

        except Exception as e:
            logger.error(f"[bedrock] Session error: {e}")
            traceback.print_exc()
            self.send_json({"type": "error", "message": f"Nova Sonic error: {e}"})
            self.is_active = False
            self.stream_response = None

    # ── Handle Audio ────────────────────────────────────────────────────

    async def handle_audio_input(self, pcm_buffer: bytes):
        """Convert PCM buffer to base64 and send as audioInput event."""
        if not self.is_active:
            logger.debug("[bedrock] handle_audio_input called but session not active")
            return

        b64_audio = base64.b64encode(pcm_buffer).decode("utf-8")
        self._audio_chunks_forwarded += 1
        if self._audio_chunks_forwarded % 50 == 1:
            logger.info(f"[bedrock] ← browser audio: chunk #{self._audio_chunks_forwarded} ({len(pcm_buffer)} bytes)")

        await self.push_event({
            "event": {
                "audioInput": {
                    "promptName": self.prompt_name,
                    "contentName": self.audio_content_name,
                    "content": b64_audio,
                }
            }
        })

    # ── Stop Session ────────────────────────────────────────────────────

    async def stop(self):
        """Gracefully close the Bedrock stream."""
        if not self.is_active:
            return

        logger.info("[bedrock] Stopping session...")
        self.is_active = False

        try:
            if self.stream_response is not None:
                # 1. Close the audio content stream
                await self.push_event_force({
                    "event": {
                        "contentEnd": {
                            "promptName": self.prompt_name,
                            "contentName": self.audio_content_name,
                        }
                    }
                })
                logger.info("[bedrock] → contentEnd (audio)")
                await asyncio.sleep(0.5)

                # 2. End the prompt
                await self.push_event_force({
                    "event": {
                        "promptEnd": {
                            "promptName": self.prompt_name,
                        }
                    }
                })
                logger.info("[bedrock] → promptEnd")
                await asyncio.sleep(0.3)

                # 3. End the session
                await self.push_event_force({
                    "event": {
                        "sessionEnd": {}
                    }
                })
                logger.info("[bedrock] → sessionEnd")
                await asyncio.sleep(0.3)

                # Close the input stream
                try:
                    await self.stream_response.input_stream.close()
                except Exception:
                    pass

        except Exception as e:
            logger.error(f"[bedrock] Error stopping session: {e}")

        # Cancel response task
        if self.response_task and not self.response_task.done():
            self.response_task.cancel()
            try:
                await self.response_task
            except (asyncio.CancelledError, Exception):
                pass

        # Cancel sender task
        if self.sender_task and not self.sender_task.done():
            self.sender_task.cancel()
            try:
                await self.sender_task
            except (asyncio.CancelledError, Exception):
                pass

        # Cancel audio flush task
        if self._audio_flush_task and not self._audio_flush_task.done():
            self._audio_flush_task.cancel()
            try:
                await self._audio_flush_task
            except (asyncio.CancelledError, Exception):
                pass
                
        # Cancel text trickle task
        if hasattr(self, "_text_trickle_task") and self._text_trickle_task and not self._text_trickle_task.done():
            self._text_trickle_task.cancel()
            try:
                await self._text_trickle_task
            except (asyncio.CancelledError, Exception):
                pass
        self._audio_accum.clear()

        self.stream_response = None
        self.response_task = None
        self.sender_task = None
        self._audio_flush_task = None
        self._text_trickle_task = None
        logger.info("[bedrock] Session stopped")

    async def handle_interrupt(self):
        """Silences the current AI output."""
        self.is_interrupted = True
        self._audio_accum.clear()
        self.audio_buffer.clear()

# ─── WebSocket Endpoint ──────────────────────────────────────────────────────

@app.websocket("/ws")
async def websocket_endpoint(ws: WebSocket):
    await ws.accept()
    logger.info("[ws] Client connected")

    session = BedrockSession(ws, agent=agent_core)

    try:
        while True:
            message = await ws.receive()

            if message["type"] == "websocket.receive":
                if "bytes" in message and message["bytes"]:
                    # Binary audio data from browser
                    await session.handle_audio_input(message["bytes"])
                elif "text" in message and message["text"]:
                    # JSON control message from browser
                    try:
                        data = json.loads(message["text"])
                        msg_type = data.get("type")

                        if msg_type == "session_start":
                            # Extract username from JWT token if provided
                            token = data.get("token")
                            if token:
                                try:
                                    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
                                    session.user_id = payload.get("sub")
                                    logger.info(f"[ws] Session user identified: {session.user_id}")
                                except Exception:
                                    logger.warning("[ws] Could not decode token from session_start")
                            # Run in background so it doesn't block the WS loop
                            asyncio.create_task(session.start())
                        elif msg_type == "session_stop":
                            await session.stop()
                            session.send_json({"type": "state", "value": "idle"})
                        else:
                            logger.info(f"[ws] Unknown message type: {msg_type}")

                    except json.JSONDecodeError as e:
                        logger.error(f"[ws] Failed to parse message: {e}")

            elif message["type"] == "websocket.disconnect":
                break

    except WebSocketDisconnect:
        pass
    except Exception as e:
        logger.error(f"[ws] WebSocket error: {e}")
    finally:
        logger.info("[ws] Client disconnected")
        await session.stop()
        # Clean up short-term memory for this session
        agent_core.clear_session(session.session_id)


# ─── Startup Banner ──────────────────────────────────────────────────────────

@app.on_event("startup")
async def startup_banner():
    init_db()
    init_telemetry()

    stats = agent_core.get_stats()
    ltm_stats = stats["long_term"]
    logger.info(f"""
  ╔══════════════════════════════════════════╗
  ║     VOICE AI ASSISTANT + AGENT CORE      ║
  ║──────────────────────────────────────────║
  ║  Status:  Running                        ║
  ║  Port:    {str(PORT).ljust(33)}║
  ║  URL:     http://localhost:{str(PORT).ljust(14)}║
  ║  Model:   Amazon Nova Sonic v1           ║
  ║  Region:  {str(AWS_REGION).ljust(33)}║
  ║  Runtime: FastAPI + Uvicorn              ║
  ║──────────────────────────────────────────║
  ║  Agent Core:  ACTIVE                     ║
  ║  Short-Term:  In-Memory (TF-IDF)         ║
  ║  Long-Term:   FAISS ({str(ltm_stats['total_vectors']).ljust(4)} vectors)       ║
  ║  Documents:   {str(ltm_stats['total_documents']).ljust(4)} indexed             ║
  ║  Knowledge:   {KNOWLEDGE_DOCS_DIR.ljust(27)}║
  ╚══════════════════════════════════════════╝
    """)

    # Auto-ingest documents from knowledge_docs/ directory
    # Run in a background thread so it doesn't block Uvicorn startup (FAISS can be slow on Windows)
    async def run_auto_ingest():
        try:
            # Run the synchronous function in a thread pool
            await asyncio.to_thread(auto_ingest_documents)
        except Exception as e:
            logger.error(f"[AutoIngest] Failed during startup: {e}")
            traceback.print_exc()

    asyncio.create_task(run_auto_ingest())
